<?php
/**
 * MessagingOutgoingChatCloseEventTypeEventDataTest
 *
 * PHP version 5
 *
 * @category Class
 * @package  VoximplantKitIM
 * @author   Swagger Codegen team
 * @link     https://github.com/swagger-api/swagger-codegen
 */

/**
 * Voximplant Kit Messaging API Documentation
 *
 * <h1>Basic description</h1>  <p>HTTP API is available via the <u>https://kit-im-{{region}}.voximplant.com/<b>{method}</b></u> endpoint. To send events you need to use jwt token. You can get jwt token via login method using an api token created on api tokens page. You need to pass api token as access_token.</p>  <h1>Authentication</h1>   <p>The parameters that are needed to be sent for generate jwt token are as follows:</p> <ul>   <li><strong>access_token</strong></li>   <li><strong>domain</strong></li> </ul>
 *
 * OpenAPI spec version: 2.0
 * 
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 * Swagger Codegen version: 3.0.24
 */

/**
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen
 * Please update the test case below to test the model.
 */

namespace VoximplantKitIM;

/**
 * MessagingOutgoingChatCloseEventTypeEventDataTest Class Doc Comment
 *
 * @category    Class
 * @description MessagingOutgoingChatCloseEventTypeEventData
 * @package     VoximplantKitIM
 * @author      Swagger Codegen team
 * @link        https://github.com/swagger-api/swagger-codegen
 */
class MessagingOutgoingChatCloseEventTypeEventDataTest extends \PHPUnit_Framework_TestCase
{

    /**
     * Setup before running any test case
     */
    public static function setUpBeforeClass()
    {
    }

    /**
     * Setup before running each test case
     */
    public function setUp()
    {
    }

    /**
     * Clean up after running each test case
     */
    public function tearDown()
    {
    }

    /**
     * Clean up after running all test cases
     */
    public static function tearDownAfterClass()
    {
    }

    /**
     * Test "MessagingOutgoingChatCloseEventTypeEventData"
     */
    public function testMessagingOutgoingChatCloseEventTypeEventData()
    {
    }

    /**
     * Test attribute "close_reason"
     */
    public function testPropertyCloseReason()
    {
    }

    /**
     * Test attribute "sender_data"
     */
    public function testPropertySenderData()
    {
    }
}
