<?php
/**
 * MessagingIncomingEventTypeClientDataTest
 *
 * PHP version 5
 *
 * @category Class
 * @package  VoximplantKitIM
 * @author   Swagger Codegen team
 * @link     https://github.com/swagger-api/swagger-codegen
 */

/**
 * Voximplant Kit Messaging API Documentation
 *
 * <h1>Basic description</h1>  <p>HTTP API is available via the <u>https://kit-im-{{region}}.voximplant.com/<b>{method}</b></u> endpoint. To send events you need to use jwt token. You can get jwt token via login method using an api token created on api tokens page. You need to pass api token as access_token.</p>  <h1>Authentication</h1>   <p>The parameters that are needed to be sent for generate jwt token are as follows:</p> <ul>   <li><strong>access_token</strong></li>   <li><strong>domain</strong></li> </ul>
 *
 * OpenAPI spec version: 2.0
 * 
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 * Swagger Codegen version: 3.0.24
 */

/**
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen
 * Please update the test case below to test the model.
 */

namespace VoximplantKitIM;

/**
 * MessagingIncomingEventTypeClientDataTest Class Doc Comment
 *
 * @category    Class
 * @description MessagingIncomingEventTypeClientData
 * @package     VoximplantKitIM
 * @author      Swagger Codegen team
 * @link        https://github.com/swagger-api/swagger-codegen
 */
class MessagingIncomingEventTypeClientDataTest extends \PHPUnit_Framework_TestCase
{

    /**
     * Setup before running any test case
     */
    public static function setUpBeforeClass()
    {
    }

    /**
     * Setup before running each test case
     */
    public function setUp()
    {
    }

    /**
     * Clean up after running each test case
     */
    public function tearDown()
    {
    }

    /**
     * Clean up after running all test cases
     */
    public static function tearDownAfterClass()
    {
    }

    /**
     * Test "MessagingIncomingEventTypeClientData"
     */
    public function testMessagingIncomingEventTypeClientData()
    {
    }

    /**
     * Test attribute "client_id"
     */
    public function testPropertyClientId()
    {
    }

    /**
     * Test attribute "client_phone"
     */
    public function testPropertyClientPhone()
    {
    }

    /**
     * Test attribute "client_avatar"
     */
    public function testPropertyClientAvatar()
    {
    }

    /**
     * Test attribute "client_display_name"
     */
    public function testPropertyClientDisplayName()
    {
    }

    /**
     * Test attribute "client_email"
     */
    public function testPropertyClientEmail()
    {
    }

    /**
     * Test attribute "client_language"
     */
    public function testPropertyClientLanguage()
    {
    }

    /**
     * Test attribute "utm"
     */
    public function testPropertyUtm()
    {
    }

    /**
     * Test attribute "page"
     */
    public function testPropertyPage()
    {
    }

    /**
     * Test attribute "location"
     */
    public function testPropertyLocation()
    {
    }

    /**
     * Test attribute "device"
     */
    public function testPropertyDevice()
    {
    }
}
